language: php

php:
  - 5.2
  - 5.3
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - cd ..
  - ls
  - drush dl coder-7.x-2.x-dev
  - cd ggp_profile
  - pwd
  - drush make ggp_net.build ../beta.ggp.com
  - cd ../beta.ggp.com
  - pwd
  - sudo chmod -R 777 sites/all/modules
  - drush si ggp_net --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="beta.ggp.com" --yes
  - drush cc all --yes
  - pwd
  - cd ../ggp_profile
  - pwd

script: 
  - test -d ../beta.ggp.com/profiles/ggp_net
  - test -d ../beta.ggp.com/profiles/ggp_net/modules/jquery_update
  - test -d ../beta.ggp.com/profiles/ggp_net/libraries/fancybox
  - test -d ../beta.ggp.com/profiles/ggp_net/themes
  - phpcs . --standard=../coder/coder_sniffer/Drupal/ruleset.xml --extensions=php,module,inc,install,test,profile,theme
