language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear install PHP_CodeSniffer
  - wget http://ftp.drupal.org/files/projects/drupalcs-7.x-1.0-beta1.tar.gz -O ../drupalcs.tar.gz
  - tar -xvzf ../drupalcs.tar.gz -C ../
  - pwd
  - phpenv rehash
  - drush make ggp_net.build ../beta.ggp.com
  - cd ../beta.ggp.com
  - sudo chmod -R 777 sites/all/modules
  - drush si ggp_net --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="beta.ggp.com" --yes
  - drush cc all --yes
  - cd ../ggp_profile

script: 
  - test -d ../beta.ggp.com/profiles/ggp_net
  - test -d ../beta.ggp.com/profiles/ggp_net/modules/contrib
  - test -d ../beta.ggp.com/profiles/ggp_net/modules/vih
  - test -d ../beta.ggp.com/profiles/ggp_net/themes
  - phpcs . --standard=../drupalcs/Drupal/ruleset.xml --extensions=php,module,inc,install,test,profile,theme
