; This file was auto-generated by drush_make
core = 7.x
api = 2

; Modules
projects[ctools][subdir] = "profiles/ggp_net/modules/ctools"
projects[ctools][version] = "1.0"

projects[media][subdir] = "profiles/ggp_net/modules/media"
projects[media][version] = "1.2"

projects[colorbox][subdir] = "profiles/ggp_net/modules/colorbox"
projects[colorbox][version] = 1.3

projects[ggp][download][type] = git
projects[ggp][download][url] = https://github.com/GlobalGameport/ggp_module.git
projects[ggp][version] = 1.x-dev
projects[ggp][type] = "module"
projects[ggp][subdir] = "profiles/ggp_net/modules/ggp"

projects[libraries][subdir] = "profiles/ggp_net/modules/libraries"
projects[libraries][version] = "1.0"

projects[media_browser_plus][subdir] = "profiles/ggp_net/modules/media_browser_plus"
projects[media_browser_plus][version] = "1.0-beta3"

projects[media_gallery][subdir] = "profiles/ggp_net/modules/media_gallery"
projects[media_gallery][version] = "1.0-beta8"

projects[metatag][subdir] = "profiles/ggp_net/modules/metatag"
projects[metatag][version] = "1.0-alpha3"

projects[multiform][subdir] = "profiles/ggp_net/modules/multiform"
projects[multiform][version] = "1.0"

projects[navigation404][subdir] = "profiles/ggp_net/modules/navigation404"
projects[navigation404][version] = "1.0"

projects[pathauto][subdir] = "profiles/ggp_net/modules/pathauto"
projects[pathauto][version] = "1.0"

projects[piwik][subdir] = "profiles/ggp_net/modules/piwik"
projects[piwik][version] = "2.3"

projects[redirect][subdir] = "profiles/ggp_net/modules/redirect"
projects[redirect][version] = "1.0-beta4"

projects[token][subdir] = "profiles/ggp_net/modules/token"
projects[token][version] = "1.0"

projects[views][subdir] = "profiles/ggp_net/modules/views"
projects[views][version] = "3.3"

projects[media_oembed_thumbnail_style][download][type] = ""
projects[media_oembed_thumbnail_style][download][url] = ""
projects[media_oembed_thumbnail_style][type] = "module"

; Themes
projects[adaptivetheme][subdir] = "profiles/ggp_net/themes/adaptivetheme"
projects[adaptivetheme][version] = "2.2"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ggp_theme][download][type] = git
projects[ggp_theme][download][url] = https://github.com/GlobalGameport/ggp_theme.git
projects[ggp_theme][type] = "theme"
projects[ggp_theme][subdir] = "profiles/ggp_net/themes/ggp_theme"
projects[ggp_theme][version] = "1.0"


; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url] = http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.5/ckeditor_3.5.tar.gz
libraries[ckeditor][type] = "library"

libraries[fancybox][download][type] = ""
libraries[fancybox][download][url] = ""
libraries[fancybox][directory_name] = "fancybox"
libraries[fancybox][type] = "library"

libraries[jquery.imgareaselect][download][type] = ""
libraries[jquery.imgareaselect][download][url] = ""
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

libraries[plupload][download][type] = get
libraries[plupload][download][url] = http://www.plupload.com/plupload_1_3_0.zip
libraries[plupload][directory_name] = plupload
libraries[plupload][type] = "library"

libraries[colorbox][download][type] = get
libraries[colorbox][download][url] = http://colorpowered.com/colorbox/colorbox.zip
libraries[colorbox][type] = "library"

libraries[plupload][download][type] = get
libraries[plupload][download][url] = http://www.plupload.com/plupload_1_3_0.zip
libraries[plupload][directory_name] = plupload